/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    DriftRebalanceStrategy: {
      address: "0xfFFc7Da411a899e8c76fc4546D63e8e38Fc55D64",
      abi: [
        {
          inputs: [
            {
              internalType: "int24",
              name: "tick",
              type: "int24",
            },
          ],
          name: "TickOutOfBounds",
          type: "error",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "vault",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "assetA",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "assetB",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "router",
                  type: "address",
                },
                {
                  internalType: "uint24",
                  name: "fee",
                  type: "uint24",
                },
                {
                  internalType: "uint16",
                  name: "targetBpsA",
                  type: "uint16",
                },
                {
                  internalType: "uint16",
                  name: "bandBps",
                  type: "uint16",
                },
                {
                  internalType: "uint256",
                  name: "minTradeValue1e18",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "slippageBps",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "decimalsA",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "decimalsB",
                  type: "uint8",
                },
                {
                  components: [
                    {
                      internalType: "address",
                      name: "pool",
                      type: "address",
                    },
                    {
                      internalType: "uint32",
                      name: "twapWindow",
                      type: "uint32",
                    },
                    {
                      internalType: "address",
                      name: "feed",
                      type: "address",
                    },
                    {
                      internalType: "uint256",
                      name: "maxFeedAge",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "maxDivergenceBps",
                      type: "uint256",
                    },
                    {
                      internalType: "bool",
                      name: "assetIsToken0",
                      type: "bool",
                    },
                    {
                      internalType: "uint8",
                      name: "assetDecimals",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "quoteDecimals",
                      type: "uint8",
                    },
                  ],
                  internalType: "struct PriceGuard.Sources",
                  name: "sources",
                  type: "tuple",
                },
              ],
              internalType: "struct DriftRebalanceStrategy.Config",
              name: "c",
              type: "tuple",
            },
          ],
          name: "encodeConfig",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "explain",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "inspect",
          outputs: [
            {
              components: [
                {
                  internalType: "bool",
                  name: "priced",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "reason",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "price",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "balanceA",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "balanceB",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalValue",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "currentBpsA",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "driftBps",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "overweightA",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "tradeValue",
                  type: "uint256",
                },
              ],
              internalType: "struct DriftRebalanceStrategy.Position",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "nextInterval",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "plan",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "target",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "value",
                  type: "uint256",
                },
                {
                  internalType: "bytes",
                  name: "data",
                  type: "bytes",
                },
              ],
              internalType: "struct INocturneStrategy.Action[]",
              name: "actions",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "validateConfig",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {
        explain: "contracts/interfaces/INocturneStrategy.sol",
        nextInterval: "contracts/interfaces/INocturneStrategy.sol",
        plan: "contracts/interfaces/INocturneStrategy.sol",
        validateConfig: "contracts/interfaces/INocturneStrategy.sol",
      },
      deployedOnBlock: 40910344,
    },
    Heartbeat: {
      address: "0x8b63C92F7d906862922D060C7Ffc294d8a43ec0b",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "beat",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "by",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "at",
              type: "uint256",
            },
          ],
          name: "Beat",
          type: "event",
        },
        {
          inputs: [],
          name: "beat",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "beats",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lastBeatAt",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lastBeatBy",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "silenceFor",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40889899,
    },
    HeartbeatStrategy: {
      address: "0xA5638e6682e2FDCC89CEE92Ffc9EC98F3D602428",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "heartbeat",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "intervalSeconds",
              type: "uint256",
            },
          ],
          name: "encodeConfig",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "explain",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "nextInterval",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "plan",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "target",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "value",
                  type: "uint256",
                },
                {
                  internalType: "bytes",
                  name: "data",
                  type: "bytes",
                },
              ],
              internalType: "struct INocturneStrategy.Action[]",
              name: "actions",
              type: "tuple[]",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "validateConfig",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {
        explain: "contracts/interfaces/INocturneStrategy.sol",
        nextInterval: "contracts/interfaces/INocturneStrategy.sol",
        plan: "contracts/interfaces/INocturneStrategy.sol",
        validateConfig: "contracts/interfaces/INocturneStrategy.sol",
      },
      deployedOnBlock: 40892384,
    },
    NocturneFactory: {
      address: "0xc0f202Ac01475AFBD07e09643d56bdacC9294B78",
      abi: [
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "vault",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "strategy",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "funded",
              type: "uint256",
            },
          ],
          name: "VaultCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "allVaults",
          outputs: [
            {
              internalType: "address[]",
              name: "page",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "strategy",
              type: "address",
            },
          ],
          name: "createVault",
          outputs: [
            {
              internalType: "address",
              name: "vault",
              type: "address",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "latestVaultOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalVaults",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "vaultCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "vaultOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "vaultsOf",
          outputs: [
            {
              internalType: "address[]",
              name: "page",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "vaultsOf",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40910348,
    },
    PriceLens: {
      address: "0x7F017Bd04879389b2A9CEeD5941EeE75aD28cCdb",
      abi: [
        {
          inputs: [
            {
              internalType: "int24",
              name: "tick",
              type: "int24",
            },
          ],
          name: "TickOutOfBounds",
          type: "error",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "bool",
                  name: "agreed",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "twap",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "feed",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "divergenceBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "feedAge",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "reason",
                  type: "string",
                },
              ],
              internalType: "struct PriceGuard.Reading",
              name: "reading",
              type: "tuple",
            },
            {
              internalType: "bool",
              name: "sellingAsset",
              type: "bool",
            },
          ],
          name: "actionablePrice",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "pool",
                  type: "address",
                },
                {
                  internalType: "uint32",
                  name: "twapWindow",
                  type: "uint32",
                },
                {
                  internalType: "address",
                  name: "feed",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "maxFeedAge",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxDivergenceBps",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "assetIsToken0",
                  type: "bool",
                },
                {
                  internalType: "uint8",
                  name: "assetDecimals",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "quoteDecimals",
                  type: "uint8",
                },
              ],
              internalType: "struct PriceGuard.Sources",
              name: "sources",
              type: "tuple",
            },
          ],
          name: "read",
          outputs: [
            {
              components: [
                {
                  internalType: "bool",
                  name: "agreed",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "twap",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "feed",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "divergenceBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "feedAge",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "reason",
                  type: "string",
                },
              ],
              internalType: "struct PriceGuard.Reading",
              name: "reading",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40910353,
    },
    ProtectiveExitStrategy: {
      address: "0x699Ec374cb2b6BaBb809cB70E58018E5f6be3E59",
      abi: [
        {
          inputs: [
            {
              internalType: "int24",
              name: "tick",
              type: "int24",
            },
          ],
          name: "TickOutOfBounds",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "cadence",
          outputs: [
            {
              internalType: "uint256",
              name: "distance1e18",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "intervalSeconds",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "vault",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "asset",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "quote",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "router",
                  type: "address",
                },
                {
                  internalType: "uint24",
                  name: "fee",
                  type: "uint24",
                },
                {
                  internalType: "uint256",
                  name: "floorPrice1e18",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "slippageBps",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "assetDecimals",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "quoteDecimals",
                  type: "uint8",
                },
                {
                  components: [
                    {
                      internalType: "address",
                      name: "pool",
                      type: "address",
                    },
                    {
                      internalType: "uint32",
                      name: "twapWindow",
                      type: "uint32",
                    },
                    {
                      internalType: "address",
                      name: "feed",
                      type: "address",
                    },
                    {
                      internalType: "uint256",
                      name: "maxFeedAge",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "maxDivergenceBps",
                      type: "uint256",
                    },
                    {
                      internalType: "bool",
                      name: "assetIsToken0",
                      type: "bool",
                    },
                    {
                      internalType: "uint8",
                      name: "assetDecimals",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "quoteDecimals",
                      type: "uint8",
                    },
                  ],
                  internalType: "struct PriceGuard.Sources",
                  name: "sources",
                  type: "tuple",
                },
              ],
              internalType: "struct ProtectiveExitStrategy.Config",
              name: "c",
              type: "tuple",
            },
          ],
          name: "encodeConfig",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "explain",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "nextInterval",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "plan",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "target",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "value",
                  type: "uint256",
                },
                {
                  internalType: "bytes",
                  name: "data",
                  type: "bytes",
                },
              ],
              internalType: "struct INocturneStrategy.Action[]",
              name: "actions",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "config",
              type: "bytes",
            },
          ],
          name: "validateConfig",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {
        explain: "contracts/interfaces/INocturneStrategy.sol",
        nextInterval: "contracts/interfaces/INocturneStrategy.sol",
        plan: "contracts/interfaces/INocturneStrategy.sol",
        validateConfig: "contracts/interfaces/INocturneStrategy.sol",
      },
      deployedOnBlock: 40910339,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
