/**
 * Exports the ABIs of contracts that are created at runtime rather than deployed.
 *
 * Scaffold's own `generateTsAbis` reads `deployments/`, so it only ever sees
 * contracts a deploy script put there. A vault has no deployment record: the
 * factory creates one per owner, whenever an owner asks, at an address nobody
 * knew in advance. The frontend still needs its ABI — it just supplies the
 * address itself, from `NocturneFactory.latestVaultOf`.
 *
 * So this writes a second, address-less file next to `deployedContracts.ts`,
 * straight from the compiler's artifacts. It runs on every `hardhat deploy`,
 * which keeps it honest: change the vault's interface and the frontend's types
 * change with it, instead of drifting until something fails in a browser.
 */

import * as fs from "fs";
import * as path from "path";
import prettier from "prettier";
import { HardhatRuntimeEnvironment } from "hardhat/types";

/** Contracts the frontend talks to but never deploys. */
const RUNTIME_CONTRACTS = ["NocturneVault"];

const TARGET = path.join(__dirname, "../../nextjs/contracts/runtimeContracts.ts");

const header = `
/**
 * This file is autogenerated by scripts/generateRuntimeAbis.ts.
 *
 * These contracts are created at runtime by a factory, so they have no fixed
 * address and no deployment record. Supply the address at the call site.
 */
`;

export async function generateRuntimeAbis(hre: HardhatRuntimeEnvironment) {
  const entries: string[] = [];

  for (const name of RUNTIME_CONTRACTS) {
    const { abi } = await hre.artifacts.readArtifact(name);
    entries.push(`${name}: { abi: ${JSON.stringify(abi, null, 2)} }`);
  }

  const source = `${header}
const runtimeContracts = { ${entries.join(",\n")} } as const;

export default runtimeContracts;
`;

  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, await prettier.format(source, { parser: "typescript" }));

  console.log("📝 Updated runtime contract ABIs at packages/nextjs/contracts/runtimeContracts.ts");
}

export default generateRuntimeAbis;
